version: '3.8'
services:
  eureka-server:
    image: eurekaserver
    container_name: eureka-server
    build:
      context: ../eureka_server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - eureka-net


  catalogo-veiculos:
    image: catalogoveiculos
    container_name: catalogo-veiculos
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - eureka-net

networks:
  eureka-net: