apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogo-veiculos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogo-veiculos
  template:
    metadata:
      labels:
        app: catalogo-veiculos
    spec:
      containers:
        - name: catalogo-veiculos
          image: catalogoveiculos:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_SERVER_URI
              value: "http://eureka-server:8761/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogo-veiculos
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31001
  selector:
    app: catalogo-veiculos
